### ISSUE TITLE
Problems running dev:run command

### ISSUE THREAD

**Issue by rorteg** [vendure-ecommerce/plugin-template#24]
When running the command:
`yarn dev:run`

```
dev-server_database_1 is up-to-date
Starting dev-server_worker_1 ... done
Recreating dev-server_server_1 ... done
Attaching to dev-server_database_1, dev-server_worker_1, dev-server_server_1
worker_1    | yarn run v1.22.17
worker_1    | $ ts-node ./dev-server/index-worker.ts
database_1  | 
database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1  | 
database_1  | 2022-03-05 16:59:15.387 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database_1  | 2022-03-05 16:59:15.390 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1  | 2022-03-05 16:59:15.391 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1  | 2022-03-05 16:59:15.420 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1  | 2022-03-05 16:59:15.578 UTC [26] LOG:  database system was shut down at 2022-03-05 16:38:39 UTC
database_1  | 2022-03-05 16:59:15.713 UTC [1] LOG:  database system is ready to accept connections
database_1  | 2022-03-05 17:01:35.176 UTC [35] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:01:35.176 UTC [35] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
database_1  | 2022-03-05 17:01:35.452 UTC [36] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:01:35.452 UTC [36] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:01:35.505 UTC [36] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:01:35.505 UTC [36] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
database_1  | 2022-03-05 17:03:28.573 UTC [39] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:03:28.573 UTC [39] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
database_1  | 2022-03-05 17:03:29.713 UTC [40] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:03:29.713 UTC [40] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:03:29.796 UTC [40] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:03:29.796 UTC [40] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
database_1  | 
database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1  | 
database_1  | 2022-03-05 17:14:49.809 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database_1  | 2022-03-05 17:14:49.811 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1  | 2022-03-05 17:14:49.811 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1  | 2022-03-05 17:14:49.852 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1  | 2022-03-05 17:14:49.968 UTC [27] LOG:  database system was interrupted; last known up at 2022-03-05 17:04:15 UTC
database_1  | 2022-03-05 17:15:00.710 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
database_1  | 2022-03-05 17:15:00.810 UTC [27] LOG:  redo starts at 0/16FB9D0
database_1  | 2022-03-05 17:15:00.816 UTC [27] LOG:  invalid record length at 0/16FBAB8: wanted 24, got 0
database_1  | 2022-03-05 17:15:00.817 UTC [27] LOG:  redo done at 0/16FBA80 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
database_1  | 2022-03-05 17:15:00.955 UTC [1] LOG:  database system is ready to accept connections
database_1  | 2022-03-05 17:15:50.843 UTC [34] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:15:50.843 UTC [34] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
database_1  | 2022-03-05 17:15:51.090 UTC [36] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:15:51.090 UTC [36] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:15:51.137 UTC [36] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:15:51.137 UTC [36] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
database_1  | 2022-03-05 17:15:52.721 UTC [35] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:15:52.721 UTC [35] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
database_1  | 2022-03-05 17:15:53.135 UTC [37] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:15:53.135 UTC [37] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:15:53.241 UTC [37] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:15:53.241 UTC [37] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
database_1  | 
database_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1  | 
database_1  | 2022-03-05 17:24:10.081 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database_1  | 2022-03-05 17:24:10.085 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1  | 2022-03-05 17:24:10.085 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1  | 2022-03-05 17:24:10.100 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1  | 2022-03-05 17:24:10.173 UTC [27] LOG:  database system was interrupted; last known up at 2022-03-05 17:15:00 UTC
database_1  | 2022-03-05 17:24:16.096 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
database_1  | 2022-03-05 17:24:16.137 UTC [27] LOG:  redo starts at 0/16FBB30
database_1  | 2022-03-05 17:24:16.138 UTC [27] LOG:  invalid record length at 0/16FBB68: wanted 24, got 0
database_1  | 2022-03-05 17:24:16.138 UTC [27] LOG:  redo done at 0/16FBB30 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
database_1  | 2022-03-05 17:24:16.260 UTC [1] LOG:  database system is ready to accept connections
server_1    | yarn run v1.22.17
server_1    | $ ts-node ./dev-server/index.ts
worker_1    | info 3/5/22, 5:25 PM - [Vendure Worker] Bootstrapping Vendure Worker (pid: 29)... 
server_1    | info 3/5/22, 5:25 PM - [Vendure Server] Bootstrapping Vendure Server (pid: 29)... 
database_1  | 2022-03-05 17:25:16.933 UTC [34] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:25:16.933 UTC [34] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
worker_1    | QueryFailedError: relation "zone" does not exist
worker_1    |     at new QueryFailedError (/usr/src/app/src/error/QueryFailedError.ts:9:9)
worker_1    |     at PostgresQueryRunner.<anonymous> (/usr/src/app/src/driver/postgres/PostgresQueryRunner.ts:228:19)
worker_1    |     at step (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
worker_1    |     at Object.throw (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
worker_1    |     at rejected (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
worker_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
worker_1    |   length: 104,
worker_1    |   severity: 'ERROR',
worker_1    |   code: '42P01',
worker_1    |   detail: undefined,
worker_1    |   hint: undefined,
worker_1    |   position: '890',
worker_1    |   internalPosition: undefined,
worker_1    |   internalQuery: undefined,
worker_1    |   where: undefined,
worker_1    |   schema: undefined,
worker_1    |   table: undefined,
worker_1    |   column: undefined,
worker_1    |   dataType: undefined,
worker_1    |   constraint: undefined,
worker_1    |   file: 'parse_relation.c',
worker_1    |   line: '1381',
worker_1    |   routine: 'parserOpenTable',
worker_1    |   query: 'SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"',
worker_1    |   parameters: []
worker_1    | }
database_1  | 2022-03-05 17:25:17.182 UTC [37] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:25:17.182 UTC [37] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:25:17.254 UTC [37] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:25:17.254 UTC [37] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
server_1    | info 3/5/22, 5:25 PM - [AssetServerPlugin] Creating asset server middleware 
server_1    | info 3/5/22, 5:25 PM - [AdminUiPlugin] Creating admin ui middleware (dev mode) 
server_1    | info 3/5/22, 5:25 PM - [AdminUiPlugin] Compiling Admin UI app in development mode 
server_1    | info 3/5/22, 5:25 PM - [RoutesResolver] HealthController {/health}: 
server_1    | info 3/5/22, 5:25 PM - [RouterExplorer] Mapped {/health, GET} route 
database_1  | 2022-03-05 17:25:20.123 UTC [35] ERROR:  relation "zone" does not exist at character 890
database_1  | 2022-03-05 17:25:20.123 UTC [35] STATEMENT:  SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"
server_1    | QueryFailedError: relation "zone" does not exist
server_1    |     at new QueryFailedError (/usr/src/app/src/error/QueryFailedError.ts:9:9)
server_1    |     at PostgresQueryRunner.<anonymous> (/usr/src/app/src/driver/postgres/PostgresQueryRunner.ts:228:19)
server_1    |     at step (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
server_1    |     at Object.throw (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
server_1    |     at rejected (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
server_1    |   length: 104,
server_1    |   severity: 'ERROR',
server_1    |   code: '42P01',
server_1    |   detail: undefined,
server_1    |   hint: undefined,
server_1    |   position: '890',
server_1    |   internalPosition: undefined,
server_1    |   internalQuery: undefined,
server_1    |   where: undefined,
server_1    |   schema: undefined,
server_1    |   table: undefined,
server_1    |   column: undefined,
server_1    |   dataType: undefined,
server_1    |   constraint: undefined,
server_1    |   file: 'parse_relation.c',
server_1    |   line: '1381',
server_1    |   routine: 'parserOpenTable',
server_1    |   query: 'SELECT "Zone"."createdAt" AS "Zone_createdAt", "Zone"."updatedAt" AS "Zone_updatedAt", "Zone"."name" AS "Zone_name", "Zone"."id" AS "Zone_id", "Zone__members"."createdAt" AS "Zone__members_createdAt", "Zone__members"."updatedAt" AS "Zone__members_updatedAt", "Zone__members"."code" AS "Zone__members_code", "Zone__members"."enabled" AS "Zone__members_enabled", "Zone__members"."id" AS "Zone__members_id", "Zone__members_translations"."createdAt" AS "Zone__members_translations_createdAt", "Zone__members_translations"."updatedAt" AS "Zone__members_translations_updatedAt", "Zone__members_translations"."languageCode" AS "Zone__members_translations_languageCode", "Zone__members_translations"."name" AS "Zone__members_translations_name", "Zone__members_translations"."id" AS "Zone__members_translations_id", "Zone__members_translations"."baseId" AS "Zone__members_translations_baseId" FROM "zone" "Zone" LEFT JOIN "zone_members_country" "Zone_Zone__members" ON "Zone_Zone__members"."zoneId"="Zone"."id" LEFT JOIN "country" "Zone__members" ON "Zone__members"."id"="Zone_Zone__members"."countryId"  LEFT JOIN "country_translation" "Zone__members_translations" ON "Zone__members_translations"."baseId"="Zone__members"."id"',
server_1    |   parameters: []
server_1    | }
server_1    | info 3/5/22, 5:25 PM - [AdminUiPlugin] Admin UI compiling and watching for changes... 
database_1  | 2022-03-05 17:25:20.568 UTC [38] ERROR:  relation "global_settings" does not exist at character 406
database_1  | 2022-03-05 17:25:20.568 UTC [38] STATEMENT:  SELECT "GlobalSettings"."createdAt" AS "GlobalSettings_createdAt", "GlobalSettings"."updatedAt" AS "GlobalSettings_updatedAt", "GlobalSettings"."availableLanguages" AS "GlobalSettings_availableLanguages", "GlobalSettings"."trackInventory" AS "GlobalSettings_trackInventory", "GlobalSettings"."outOfStockThreshold" AS "GlobalSettings_outOfStockThreshold", "GlobalSettings"."id" AS "GlobalSettings_id" FROM "global_settings" "GlobalSettings"  LIMIT 1
database_1  | 2022-03-05 17:25:20.633 UTC [38] ERROR:  relation "global_settings" does not exist at character 13
database_1  | 2022-03-05 17:25:20.633 UTC [38] STATEMENT:  INSERT INTO "global_settings"("createdAt", "updatedAt", "availableLanguages", "trackInventory", "outOfStockThreshold") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, DEFAULT)
server_1    | $ ng serve --port=4200 --base-href=/admin/
worker_1    | Done in 51.14s.
dev-server_worker_1 exited with code 0
```

**Comment by asiz15** [comment]
Set dbConnectionOptions.synchronize to true on your vendure-config.ts

`dbConnectionOptions: {
       ...,
        synchronize: true, // turn this off for production
    },`

**Comment by rorteg** [comment]
Thanks a lot for the answer, I think it's a good idea to add this to the README documentation.

Initial build time reached 20 minutes on Mac, I'm looking forward to the Vendure 2.0 release with NX.

Again, thank you very much!
